# Vampire
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleVampire
  name: Vampire Role
#  description: mind-role-vampire-description
  components:
  - type: MindRole
    antagPrototype: Vampire
    roleType: SoloAntagonist
  - type: VampireRole

# BloodCultist
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodCultist
  name: Blood Cultist Role
#  description: mind-role-vampire-description
  components:
  - type: MindRole
    antagPrototype: BloodCultist
    roleType: TeamAntagonist
  - type: BloodCultistRole

# BloodBrother
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodBrother
  name: Blood Brother Role
#  description: mind-role-vampire-description
  components:
  - type: MindRole
    antagPrototype: BloodBrother
    roleType: TeamAntagonist
  - type: BloodBrotherRole
