name: "Labels: Approved"
on:
  pull_request_review:
    types: [submitted]
jobs:
  add_label:
    if: ${{ github.event.review.state == 'APPROVED' && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check if user is a public member
        id: check-org
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
           https://api.github.com/orgs/wega-team/public_members/${{ github.actor }})

          echo "HTTP_STATUS=$STATUS" >> $GITHUB_OUTPUT
      - name: Add label
        if: ${{ steps.check-org.outputs.HTTP_STATUS == '204' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "S: Approved"
          github_token: ${{ secrets.LABELER_PAT }}
