name: Check Merge Conflicts

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  Label:
    if: ( github.event.pull_request.draft == false ) && ( github.actor != 'IanComradeBot' )
        && ( github.event.pull_request.head.repo.full_name == github.repository )
    runs-on: ubuntu-latest
    steps:
      - name: Check for Merge Conflicts
        uses: eps1lon/actions-label-merge-conflict@v3.0.0
        with:
          dirtyLabel: "S: Merge Conflict"
          repoToken: "${{ secrets.LABELER_PAT }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
